### ISSUE TITLE
Type issue for proxL1

### ISSUE THREAD

**Issue by aTrotier** [tknopp/RegularizedLeastSquares.jl#39]
```julia
function proxL1!(x::AbstractArray{Tc}, λ::T; sparseTrafo::Trafo=nothing, kargs...) where {T, Tc <: Union{T, Complex{T}}}
```

 `λ::T` should be ` λ::Float64` ?

issue related to : https://github.com/MagneticResonanceImaging/MRIReco.jl/issues/78

**Comment by migrosser** [comment]
The restriction `Tc <: Union{T, Complex{T}}` actually makes a lot of sense because it avoids having to perform type-conversions when the element-type of `x` and `λ` don't match.
However, I agree that it would be better if one didn't have to worry about this issue when performing high-level reconstruction, e.g. in MRIReco.
A possible solution would be to update our factory method for building `Regularization`-objects, such that the type of the underlying data is taken into account. Potentially, one could even parametrize the type `Regularization` correspondingly. What do you think @tknopp ?

**Comment by aTrotier** [comment]
Yeah seems better than my option. It was just a quick fix to see if it works

**Comment by aTrotier** [comment]
closed by commit : https://github.com/MagneticResonanceImaging/MRIReco.jl/commit/b84a9eeabf4fccbadd76b5630e9f2250c46f552a
