### ISSUE TITLE
use `cg` from `IterativeSolver`

### ISSUE THREAD

**Issue by hofmannmartin** [tknopp/RegularizedLeastSquares.jl#6]
We could replace our `cg` by the version in `IterativeSolver`, where the cg is tested.

**Comment by tknopp** [comment]
agree. However, we need to check that this does not regress in some ways. This code is used in admm which is used in MRIReco.

**Comment by andreasnoack** [comment]
It's a general comment but I'm interested in the area so when I saw the packaged being registered, I decided to browse the content.

When mentioning `LinearAlgebra` it is basically https://github.com/tknopp/RegularizedLeastSquares.jl/issues/3.

It looked like you had a couple of iterative solvers so if they aren't already in `IterativeSolvers` then it would be great to contribute them there.

I hadn't noticed that you were using `LinearOperators`. I just noticed that you had some in https://github.com/tknopp/RegularizedLeastSquares.jl/tree/master/src/linearOperators and thought you were rolling your own operator type.

**Comment by tknopp** [comment]
I have fixed #3.

> It looked like you had a couple of iterative solvers so if they aren't already in IterativeSolvers then it would be great to contribute them there.

That is on purpose. Our impression is that `IterativeSolvers` is designed for square linear systems. We are targeting non-square system. And also, as far as I can tell, `IterativeSolvers` does not take regularization into account. Our iterative solvers do.

**Comment by andreasnoack** [comment]
> Our impression is that IterativeSolvers is designed for square linear systems.

I'm not sure why you'd think that. Is it written somewhere? The package includes e.g. `lsqr`.

In any case, if you think there is a need for different implementations of the iterative methods then you are, of course, free to do so but if you end up reimplementing existing functionality instead of using an contributing to existing functionality it's just inefficient use of the limited developer resources in the community.
